<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DichVuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('dich_vus')->delete();
        DB::table('dich_vus')->truncate();
        DB::table('dich_vus')->insert([
            // --- THƯƠNG HIỆU 1: Salon Tóc Modern Gent ---
            [
                'id_thuong_hieu' => 1,
                'id_danh_muc_dich_vu' => 5,
                'ten_dich_vu' => 'Cắt tóc nam',
                'don_gia' => 100000,
                'thoi_gian_du_kien' => 30,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Dịch vụ cắt tóc nam chuyên nghiệp.',
                'mo_ta_dai' => 'Bao gồm tư vấn kiểu tóc, cắt, gội massage và sấy tạo kiểu.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_thuong_hieu' => 1,
                'id_danh_muc_dich_vu' => 5,
                'ten_dich_vu' => 'Cắt tóc nữ',
                'don_gia' => 150000,
                'thoi_gian_du_kien' => 45,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Cắt tóc nữ theo yêu cầu.',
                'mo_ta_dai' => 'Thiết kế kiểu tóc phù hợp với khuôn mặt và xu hướng thời trang.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 2: Zen Spa & Massage ---
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage Body tinh dầu',
                'don_gia' => 200000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Massage thư giãn toàn thân.',
                'mo_ta_dai' => 'Sử dụng tinh dầu thiên nhiên giúp giảm căng thẳng và mệt mỏi.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage Cổ Vai Gáy',
                'don_gia' => 250000,
                'thoi_gian_du_kien' => 45,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Trị liệu vùng cổ và vai gáy.',
                'mo_ta_dai' => 'Giảm đau nhức cơ bắp do ngồi làm việc sai tư thế.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage Đá nóng',
                'don_gia' => 300000,
                'thoi_gian_du_kien' => 90,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Massage thư giãn bằng đá nóng.',
                'mo_ta_dai' => 'Giúp lưu thông khí huyết và thư giãn sâu bằng nhiệt từ đá núi lửa.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage chân',
                'don_gia' => 150000,
                'thoi_gian_du_kien' => 45,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Bấm huyệt bàn chân.',
                'mo_ta_dai' => 'Giảm nhức mỏi chân và hỗ trợ sức khỏe thông qua các huyệt đạo.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage mặt thư giãn',
                'don_gia' => 200000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Chăm sóc da mặt cơ bản.',
                'mo_ta_dai' => 'Giúp làn da săn chắc và sảng khoái sau liệu trình.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage toàn thân VIP',
                'don_gia' => 400000,
                'thoi_gian_du_kien' => 120,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Combo chăm sóc toàn diện.',
                'mo_ta_dai' => 'Gói dịch vụ massage kéo dài 120 phút giúp phục hồi năng lượng tối đa.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 3: Nail Art Studio Hoàn Mỹ ---
            [
                'id_thuong_hieu' => 3,
                'id_danh_muc_dich_vu' => 7,
                'ten_dich_vu' => 'Làm móng tay',
                'don_gia' => 100000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Chăm sóc móng tay chuyên nghiệp.',
                'mo_ta_dai' => 'Nhặt da sạch sẽ và sơn màu theo yêu cầu của khách hàng.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_thuong_hieu' => 3,
                'id_danh_muc_dich_vu' => 7,
                'ten_dich_vu' => 'Làm móng chân',
                'don_gia' => 150000,
                'thoi_gian_du_kien' => 90,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Chăm sóc móng chân chuyên nghiệp.',
                'mo_ta_dai' => 'Bao gồm vệ sinh móng, chà gót nhẹ và sơn trang trí.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 4: Clinic Plus ---
            [
                'id_thuong_hieu' => 4,
                'id_danh_muc_dich_vu' => 8,
                'ten_dich_vu' => 'Lấy nhân mụn Y khoa',
                'don_gia' => 300000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Điều trị mụn an toàn.',
                'mo_ta_dai' => 'Quy trình lấy nhân mụn vô khuẩn, hạn chế để lại vết thâm.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 5: Đa khoa Tâm Anh ---
            [
                'id_thuong_hieu' => 5,
                'id_danh_muc_dich_vu' => 9,
                'ten_dich_vu' => 'Khám tổng quát cơ bản',
                'don_gia' => 500000,
                'thoi_gian_du_kien' => 120,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Kiểm tra sức khỏe định kỳ.',
                'mo_ta_dai' => 'Bao gồm các hạng mục xét nghiệm và chẩn đoán hình ảnh cơ bản.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 6: Tai Mũi Họng Sài Gòn ---
            [
                'id_thuong_hieu' => 6,
                'id_danh_muc_dich_vu' => 10,
                'ten_dich_vu' => 'Nội soi Tai Mũi Họng',
                'don_gia' => 300000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Khám chuyên khoa bằng nội soi.',
                'mo_ta_dai' => 'Sử dụng thiết bị hiện đại để kiểm tra sâu vùng tai, mũi, họng.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 7: Nha khoa Smile ---
            [
                'id_thuong_hieu' => 7,
                'id_danh_muc_dich_vu' => 11,
                'ten_dich_vu' => 'Nhổ răng khôn',
                'don_gia' => 200000,
                'thoi_gian_du_kien' => 30,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Tiểu phẫu nhổ răng an toàn.',
                'mo_ta_dai' => 'Quy trình nhổ răng nhanh chóng, hạn chế tối đa cảm giác đau.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 8: Sửa điện Gia Định ---
            [
                'id_thuong_hieu' => 8,
                'id_danh_muc_dich_vu' => 12,
                'ten_dich_vu' => 'Vệ sinh máy lạnh',
                'don_gia' => 500000,
                'thoi_gian_du_kien' => 120,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Bảo trì máy lạnh tại nhà.',
                'mo_ta_dai' => 'Vệ sinh lưới lọc, dàn nóng lạnh và kiểm tra ga.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 3,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 9: Sửa nước 24h ---
            [
                'id_thuong_hieu' => 9,
                'id_danh_muc_dich_vu' => 13,
                'ten_dich_vu' => 'Thông nghẹt ống nước',
                'don_gia' => 300000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Sửa chữa hệ thống nước nghẹt.',
                'mo_ta_dai' => 'Xử lý các sự cố tắc nghẽn bồn rửa, đường ống thoát nước.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠキュU 10: TechPro Electronics ---
            [
                'id_thuong_hieu' => 10,
                'id_danh_muc_dich_vu' => 14,
                'ten_dich_vu' => 'Sửa chữa Laptop/PC',
                'don_gia' => 400000,
                'thoi_gian_du_kien' => 90,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Khắc phục lỗi máy tính.',
                'mo_ta_dai' => 'Cài đặt hệ điều hành và sửa lỗi phần cứng chuyên nghiệp.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 11: Paws Pet Care ---
            [
                'id_thuong_hieu' => 11,
                'id_danh_muc_dich_vu' => 15,
                'ten_dich_vu' => 'Spa thú cưng',
                'don_gia' => 200000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Tắm gội và cắt tỉa lông.',
                'mo_ta_dai' => 'Chăm sóc vệ sinh toàn diện cho chó mèo của bạn.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 3,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_thuong_hieu' => 11,
                'id_danh_muc_dich_vu' => 15,
                'ten_dich_vu' => 'Khám thú y tổng quát',
                'don_gia' => 500000,
                'thoi_gian_du_kien' => 120,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Kiểm tra sức khỏe vật nuôi.',
                'mo_ta_dai' => 'Tư vấn tiêm chủng và điều trị các bệnh lý thường gặp ở thú cưng.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 3,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 12: TMV Korea Beauty ---
            [
                'id_thuong_hieu' => 12,
                'id_danh_muc_dich_vu' => 8,
                'ten_dich_vu' => 'Nâng cơ mặt Hifu',
                'don_gia' => 5000000,
                'thoi_gian_du_kien' => 90,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Trẻ hóa da không xâm lấn.',
                'mo_ta_dai' => 'Sử dụng công nghệ Hifu giúp da săn chắc và mờ nếp nhăn.',
                'so_luong_lich_toi_da' => 5,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_thuong_hieu' => 12,
                'id_danh_muc_dich_vu' => 8,
                'ten_dich_vu' => 'Chăm sóc da mặt Oxy',
                'don_gia' => 800000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Cấp oxy tươi cho làn da.',
                'mo_ta_dai' => 'Phục hồi da sạm màu, giúp da sáng mịn và đều màu.',
                'so_luong_lich_toi_da' => 12,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 13: Điện máy Xanh Service ---
            [
                'id_thuong_hieu' => 13,
                'id_danh_muc_dich_vu' => 12,
                'ten_dich_vu' => 'Vệ sinh máy giặt',
                'don_gia' => 250000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Làm sạch lồng giặt chuyên sâu.',
                'mo_ta_dai' => 'Loại bỏ nấm mốc và vi khuẩn bám trong lồng máy giặt.',
                'so_luong_lich_toi_da' => 15,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'id_thuong_hieu' => 13,
                'id_danh_muc_dich_vu' => 12,
                'ten_dich_vu' => 'Nạp ga máy lạnh',
                'don_gia' => 150000,
                'thoi_gian_du_kien' => 30,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Bơm ga bổ sung cho điều hòa.',
                'mo_ta_dai' => 'Kiểm tra và nạp ga đúng định lượng cho máy lạnh.',
                'so_luong_lich_toi_da' => 20,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
                'created_at' => now(), 'updated_at' => now(),
            ],

            // --- THƯƠNG HIỆU 14: Pet Paradise Resort ---
            [
                'id_thuong_hieu' => 14,
                'id_danh_muc_dich_vu' => 15,
                'ten_dich_vu' => 'Khách sạn thú cưng (24h)',
                'don_gia' => 200000,
                'thoi_gian_du_kien' => 1440,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Dịch vụ lưu trú chó mèo.',
                'mo_ta_dai' => 'Phòng nghỉ sạch sẽ, đầy đủ tiện nghi và có người chăm sóc 24/7.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
                'created_at' => now(), 'updated_at' => now(),
            ],
        ]);
    }
}