<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DichVuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('dich_vus')->delete();
        DB::table('dich_vus')->truncate();
        DB::table('dich_vus')->insert([

            [
                'id_thuong_hieu' => 1,
                'id_danh_muc_dich_vu' => 5,
                'ten_dich_vu' => 'Cắt tóc nam',
                'don_gia' => 100000,
                'thoi_gian_du_kien' => 30,
                'thoi_gian_dem' => 15,
                'mo_ta_ngan' => 'Dịch vụ cắt tóc nam chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ cắt tóc nam chuyên nghiệp với đội ngũ thợ cắt tay nghề cao, sử dụng các kỹ thuật hiện đại để tạo kiểu tóc phù hợp với khuôn mặt và phong cách của khách hàng.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
            ],
            [
                'id_thuong_hieu' => 1,
                'id_danh_muc_dich_vu' => 5,
                'ten_dich_vu' => 'Cắt tóc nữ',
                'don_gia' => 150000,
                'thoi_gian_du_kien' => 45,
                'thoi_gian_dem' => 20,
                'mo_ta_ngan' => 'Dịch vụ cắt tóc nữ chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ cắt tóc nữ chuyên nghiệp với đội ngũ thợ cắt tay nghề cao, sử dụng các kỹ thuật hiện đại để tạo kiểu tóc phù hợp với khuôn mặt và phong cách của khách hàng.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage thư giãn',
                'don_gia' => 200000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Dịch vụ massage thư giãn chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ massage thư giãn chuyên nghiệp với đội ngũ nhân viên tay nghề cao, sử dụng các kỹ thuật massage hiện đại để giúp khách hàng giảm căng thẳng, cải thiện tuần hoàn máu và tăng cường sức khỏe tổng thể.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage trị liệu',
                'don_gia' => 250000,
                'thoi_gian_du_kien' => 90,
                'thoi_gian_dem' => 45,
                'mo_ta_ngan' => 'Dịch vụ massage trị liệu chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ massage trị liệu chuyên nghiệp với đội ngũ nhân viên tay nghề cao, sử dụng các kỹ thuật massage hiện đại để giúp khách hàng giảm đau cơ, cải thiện tuần hoàn máu và tăng cường sức khỏe tổng thể.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage đá nóng',
                'don_gia' => 300000,
                'thoi_gian_du_kien' => 120,
                'thoi_gian_dem' => 60,
                'mo_ta_ngan' => 'Dịch vụ massage đá nóng chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ massage đá nóng chuyên nghiệp với đội ngũ nhân viên tay nghề cao, sử dụng các kỹ thuật massage hiện đại kết hợp với đá nóng để giúp khách hàng giảm căng thẳng, cải thiện tuần hoàn máu và tăng cường sức khỏe tổng thể.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage chân',
                'don_gia' => 150000,
                'thoi_gian_du_kien' => 45,
                'thoi_gian_dem' => 20,
                'mo_ta_ngan' => 'Dịch vụ massage chân chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ massage chân chuyên nghiệp với đội ngũ nhân viên tay nghề cao, sử dụng các kỹ thuật massage hiện đại để giúp khách hàng giảm căng thẳng, cải thiện tuần hoàn máu và tăng cường sức khỏe tổng thể.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage mặt',
                'don_gia' => 200000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Dịch vụ massage mặt chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ massage mặt chuyên nghiệp với đội ngũ nhân viên tay nghề cao, sử dụng các kỹ thuật massage hiện đại để giúp khách hàng giảm căng thẳng, cải thiện tuần hoàn máu và tăng cường sức khỏe tổng thể.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
            ],
            [
                'id_thuong_hieu' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_dich_vu' => 'Massage toàn thân',
                'don_gia' => 400000,
                'thoi_gian_du_kien' => 120,
                'thoi_gian_dem' => 60,
                'mo_ta_ngan' => 'Dịch vụ massage toàn thân chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ massage toàn thân chuyên nghiệp với đội ngũ nhân viên tay nghề cao, sử dụng các kỹ thuật massage hiện đại để giúp khách hàng giảm căng thẳng, cải thiện tuần hoàn máu và tăng cường sức khỏe tổng thể.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
            ],
            [
                'id_thuong_hieu' => 3,
                'id_danh_muc_dich_vu' => 7,
                'ten_dich_vu' => 'Làm móng tay',
                'don_gia' => 100000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Dịch vụ làm móng tay chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ làm móng tay chuyên nghiệp với đội ngũ nhân viên tay nghề cao, sử dụng các kỹ thuật làm móng hiện đại để giúp khách hàng có được bộ móng tay đẹp và khỏe mạnh.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
            ],
            [
                'id_thuong_hieu' => 3,
                'id_danh_muc_dich_vu' => 7,
                'ten_dich_vu' => 'Làm móng chân',
                'don_gia' => 150000,
                'thoi_gian_du_kien' => 90,
                'thoi_gian_dem' => 45,
                'mo_ta_ngan' => 'Dịch vụ làm móng chân chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ làm móng chân chuyên nghiệp với đội ngũ nhân viên tay nghề cao, sử dụng các kỹ thuật làm móng hiện đại để giúp khách hàng có được bộ móng chân đẹp và khỏe mạnh.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
            ],
          
            [
                'id_thuong_hieu' => 4,
                'id_danh_muc_dich_vu' => 8,
                'ten_dich_vu' => 'Điều trị mụn',
                'don_gia' => 300000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Dịch vụ điều trị mụn chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ điều trị mụn chuyên nghiệp với đội ngũ nhân viên tay nghề cao, sử dụng các kỹ thuật điều trị mụn hiện đại để giúp khách hàng có được làn da sạch mụn và khỏe mạnh.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,
            ],
            [
                'id_thuong_hieu' => 5,
                'id_danh_muc_dich_vu' => 9,
                'ten_dich_vu' => 'Khám sức khỏe tổng quát',
                'don_gia' => 500000,
                'thoi_gian_du_kien' => 120,
                'thoi_gian_dem' => 60,
                'mo_ta_ngan' => 'Dịch vụ khám sức khỏe tổng quát chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ khám sức khỏe tổng quát chuyên nghiệp với đội ngũ bác sĩ tay nghề cao, sử dụng các thiết bị y tế hiện đại để giúp khách hàng có được cái nhìn tổng quan về tình trạng sức khỏe của mình và phát hiện sớm các vấn đề sức khỏe tiềm ẩn.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,

            ],
            [
                'id_thuong_hieu' => 6,
                'id_danh_muc_dich_vu' => 10,
                'ten_dich_vu' => 'Khám chuyên khoa',
                'don_gia' => 300000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Dịch vụ khám chuyên khoa chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ khám chuyên khoa chuyên nghiệp với đội ngũ bác sĩ tay nghề cao, sử dụng các thiết bị y tế hiện đại để giúp khách hàng có được cái nhìn chi tiết về tình trạng sức khỏe của mình và phát hiện sớm các vấn đề sức khỏe tiềm ẩn.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,

            ],
            [
                'id_thuong_hieu' => 7,
                'id_danh_muc_dich_vu' => 11,
                'ten_dich_vu' => 'Nhổ răng',
                'don_gia' => 200000,
                'thoi_gian_du_kien' => 30,
                'thoi_gian_dem' => 15,
                'mo_ta_ngan' => 'Dịch vụ nhổ răng chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ nhổ răng chuyên nghiệp với đội ngũ bác sĩ tay nghề cao, sử dụng các thiết bị y tế hiện đại để giúp khách hàng có được trải nghiệm nhổ răng an toàn, hiệu quả và giảm thiểu đau đớn.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 1,


            ],
            [
                'id_thuong_hieu' => 8,
                'id_danh_muc_dich_vu' => 12,
                'ten_dich_vu' => 'Sửa máy lạnh',
                'don_gia' => 500000,
                'thoi_gian_du_kien' => 120,
                'thoi_gian_dem' => 60,
                'mo_ta_ngan' => 'Dịch vụ sửa máy lạnh chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ sửa máy lạnh chuyên nghiệp với đội ngũ kỹ thuật viên tay nghề cao, sử dụng các thiết bị hiện đại để giúp khách hàng có được trải nghiệm sửa máy lạnh an toàn, hiệu quả và giảm thiểu rủi ro.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 3,
            ],
            [
                'id_thuong_hieu' => 9,
                'id_danh_muc_dich_vu' => 13,
                'ten_dich_vu' => 'Sửa ống nước',
                'don_gia' => 300000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Dịch vụ sửa ống nước chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ sửa ống nước chuyên nghiệp với đội ngũ kỹ thuật viên tay nghề cao, sử dụng các thiết bị hiện đại để giúp khách hàng có được trải nghiệm sửa ống nước an toàn, hiệu quả và giảm thiểu rủi ro.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
            ],
            [
                'id_thuong_hieu' => 10,
                'id_danh_muc_dich_vu' => 14,
                'ten_dich_vu' => 'Sửa vi tính',
                'don_gia' => 400000,
                'thoi_gian_du_kien' => 90,
                'thoi_gian_dem' => 45,
                'mo_ta_ngan' => 'Dịch vụ sửa vi tính chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ sửa vi tính chuyên nghiệp với đội ngũ kỹ thuật viên tay nghề cao, sử dụng các thiết bị hiện đại để giúp khách hàng có được trải nghiệm sửa vi tính an toàn, hiệu quả và giảm thiểu rủi ro.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 2,
            ],
            [
                'id_thuong_hieu' => 11,
                'id_danh_muc_dich_vu' => 15,
                'ten_dich_vu' => 'Spa chó mèo',
                'don_gia' => 200000,
                'thoi_gian_du_kien' => 60,
                'thoi_gian_dem' => 30,
                'mo_ta_ngan' => 'Dịch vụ Spa chó mèo chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ Spa chó mèo chuyên nghiệp với đội ngũ nhân viên tay nghề cao, sử dụng các kỹ thuật chăm sóc hiện đại để giúp khách hàng có được trải nghiệm Spa chó mèo an toàn, hiệu quả và giảm thiểu rủi ro.',
                'so_luong_lich_toi_da' =>   10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 3,
            ],
            [
                'id_thuong_hieu' => 11,
                'id_danh_muc_dich_vu' => 15,
                'ten_dich_vu' => 'Bệnh viện thú y',
                'don_gia' => 500000,
                'thoi_gian_du_kien' => 120,
                'thoi_gian_dem' => 60,
                'mo_ta_ngan' => 'Dịch vụ bệnh viện thú y chuyên nghiệp',
                'mo_ta_dai' => 'Dịch vụ bệnh viện thú y chuyên nghiệp với đội ngũ bác sĩ tay nghề cao, sử dụng các thiết bị y tế hiện đại để giúp khách hàng có được trải nghiệm điều trị thú y an toàn, hiệu quả và giảm thiểu rủi ro.',
                'so_luong_lich_toi_da' => 10,
                'trang_thai' => 1,
                'kieu_phuc_vu' => 3,
            ],

        ]);
    }
}
