<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ThuongHieuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('thuong_hieus')->delete();
        DB::table('thuong_hieus')->truncate();
        DB::table('thuong_hieus')->insert([
            [
                'id_nha_cung_cap' => 1,
                'id_danh_muc_dich_vu' => 5,
                'ten_thuong_hieu' => 'Salon tóc Luxury',
                'dia_chi' => '123 Đường ABC, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0123456789',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Salon tóc chuyên nghiệp với đội ngũ thợ lành nghề và dịch vụ đa dạng.',
                'ma_so_thue' => '123456789',
                'ma_bin_ngan_hang' => '970436', 
                'tai_khoan_ngan_hang' => '0123456789',
                'diem_hai_long' => 4.8,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_thuong_hieu' => 'Spa & Massage Zen',
                'dia_chi' => '456 Đường DEF, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0987654321',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Spa&Massage cao cấp với không gian thư giãn và dịch vụ chăm sóc sức khỏe toàn diện.',
                'ma_so_thue' => '987654321',
                'ma_bin_ngan_hang' => '970415', 
                'tai_khoan_ngan_hang' => '0987654321',
                'diem_hai_long' => 4.5,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 3,
                'id_danh_muc_dich_vu' => 7,
                'ten_thuong_hieu' => 'Nail Art Studio',
                'dia_chi' => '789 Đường GHI, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0123456789',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Dịch vụ làm móng chuyên nghiệp với thiết kế sáng tạo và chất lượng cao.',
                'ma_so_thue' => '123456789',
                'ma_bin_ngan_hang' => '970418', 
                'tai_khoan_ngan_hang' => '0123456789',
                'diem_hai_long' => 4.2,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 4,
                'id_danh_muc_dich_vu' => 8,
                'ten_thuong_hieu' => 'Clinic International',
                'dia_chi' => '321 Đường JKL, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0987654321',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Clinic chuyên khoa với đội ngũ bác sĩ giàu kinh nghiệm và trang thiết bị hiện đại.',
                'ma_so_thue' => '987654321',
                'ma_bin_ngan_hang' => '970405', 
                'tai_khoan_ngan_hang' => '0987654321',
                'diem_hai_long' => 4.9,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 5,
                'id_danh_muc_dich_vu' => 9,
                'ten_thuong_hieu' => 'Bệnh viện Đa khoa Tâm Anh',
                'dia_chi' => '654 Đường MNO, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0123456789',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Bệnh viện đa khoa với dịch vụ chăm sóc sức khỏe toàn diện và đội ngũ y bác sĩ chuyên nghiệp.',
                'ma_so_thue' => '123456789',
                'ma_bin_ngan_hang' => '970422', 
                'tai_khoan_ngan_hang' => '0123456789',
                'diem_hai_long' => 4.7,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 6,
                'id_danh_muc_dich_vu' => 10,
                'ten_thuong_hieu' => 'Phòng khám Chuyên khoa',
                'dia_chi' => '987 Đường PQR, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0987654321',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Bệnh viện chuyên khoa với dịch vụ chăm sóc sức khỏe chuyên sâu và đội ngũ y bác sĩ giàu kinh nghiệm.',
                'ma_so_thue' => '987654321',
                'ma_bin_ngan_hang' => '970423', 
                'tai_khoan_ngan_hang' => '0987654321',
                'diem_hai_long' => 4.4,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 7,
                'id_danh_muc_dich_vu' => 11,
                'ten_thuong_hieu' => 'Nha khoa Smile',
                'dia_chi' => '321 Đường STU, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0123456789',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Phòng khám nha khoa với dịch vụ chăm sóc răng miệng chuyên nghiệp.',
                'ma_so_thue' => '123456789',
                'ma_bin_ngan_hang' => '970407', 
                'tai_khoan_ngan_hang' => '0123456789',
                'diem_hai_long' => 4.8,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 8,
                'id_danh_muc_dich_vu' => 12,
                'ten_thuong_hieu' => 'Sửa điện Gia Định',
                'dia_chi' => '654 Đường VWX, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0987654321',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Dịch vụ sửa chữa điện chuyên nghiệp với đội ngũ kỹ thuật viên lành nghề.',
                'ma_so_thue' => '987654321',
                'ma_bin_ngan_hang' => '970416', 
                'tai_khoan_ngan_hang' => '0987654321',
                'diem_hai_long' => 4.1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 9,
                'id_danh_muc_dich_vu' => 13,
                'ten_thuong_hieu' => 'Sửa nước 24h',
                'dia_chi' => '987 Đường YZ, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0123456789',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Dịch vụ sửa chữa nước chuyên nghiệp với đội ngũ kỹ thuật viên lành nghề.',
                'ma_so_thue' => '123456789',
                'ma_bin_ngan_hang' => '970432', 
                'tai_khoan_ngan_hang' => '0123456789',
                'diem_hai_long' => 4.3,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 10,
                'id_danh_muc_dich_vu' => 14,
                'ten_thuong_hieu' => 'Trung tâm Điện tử Tech',
                'dia_chi' => '321 Đường ZAB, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0987654321',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Dịch vụ sửa chữa điện tử chuyên nghiệp với trang thiết bị hiện đại.',
                'ma_so_thue' => '987654321',
                'ma_bin_ngan_hang' => '970441', 
                'tai_khoan_ngan_hang' => '0987654321',
                'diem_hai_long' => 4.6,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 11,
                'id_danh_muc_dich_vu' => 15,
                'ten_thuong_hieu' => 'Pet Care Center',
                'dia_chi' => '654 Đường CDE, Quận XYZ, TP.HCM',
                'so_dien_thoai' => '0123456789',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Dịch vụ chăm sóc thú cưng chuyên nghiệp với đội ngũ nhân viên yêu động vật.',
                'ma_so_thue' => '123456789',
                'ma_bin_ngan_hang' => '970429', 
                'tai_khoan_ngan_hang' => '0123456789',
                'diem_hai_long' => 4.9,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 12,
                'id_danh_muc_dich_vu' => 8,
                'ten_thuong_hieu' => 'TMV Korea Beauty',
                'dia_chi' => '456 Đường LMN, Quận 3, TP.HCM',
                'so_dien_thoai' => '0909123456',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Thẩm mỹ viện chuẩn Hàn Quốc với công nghệ trẻ hóa da hiện đại nhất.',
                'ma_so_thue' => '555666777',
                'ma_bin_ngan_hang' => '970436', 
                'tai_khoan_ngan_hang' => '999888777',
                'diem_hai_long' => 5.0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 13,
                'id_danh_muc_dich_vu' => 12,
                'ten_thuong_hieu' => 'Điện máy Xanh Service',
                'dia_chi' => '789 Đường GHI, Quận Bình Thạnh, TP.HCM',
                'so_dien_thoai' => '0908777888',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Dịch vụ sửa chữa điện lạnh tận nhà chuyên nghiệp và nhanh chóng.',
                'ma_so_thue' => '111222333',
                'ma_bin_ngan_hang' => '970422',
                'tai_khoan_ngan_hang' => '123123123',
                'diem_hai_long' => 4.2,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 14,
                'id_danh_muc_dich_vu' => 15,
                'ten_thuong_hieu' => 'Pet Paradise Resort',
                'dia_chi' => '321 Đường OPQ, Quận 7, TP.HCM',
                'so_dien_thoai' => '0907111222',
                'logo' => "https://static.vecteezy.com/system/resources/previews/021/548/095/original/default-profile-picture-avatar-user-avatar-icon-person-icon-head-icon-profile-picture-icons-default-anonymous-user-male-and-female-businessman-photo-placeholder-social-network-avatar-portrait-free-vector.jpg",
                'anh_bia' => "https://img.pikbest.com/backgrounds/20170624/beautiful-drawing-flowers-doodle-background_1818310.jpg!bwr800",
                'mo_ta' => 'Nơi nghỉ dưỡng lý tưởng và chăm sóc toàn diện cho thú cưng của bạn.',
                'ma_so_thue' => '888777999',
                'ma_bin_ngan_hang' => '970407',
                'tai_khoan_ngan_hang' => '456456456',
                'diem_hai_long' => 4.7,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}