<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ThuongHieuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('thuong_hieus')->delete();
        DB::table('thuong_hieus')->truncate();
        DB::table('thuong_hieus')->insert([
            [
                'id_nha_cung_cap' => 1,
                'id_danh_muc_dich_vu' => 5,
                'ten_thuong_hieu' => 'Salon Tóc Modern Gent',
                'dia_chi' => 'Số 15 đường số 2, Cư xá Đô Thành, Quận 3, TP.HCM',
                'so_dien_thoai' => '0901234567',
                'logo' => "https://ui-avatars.com/api/?name=Modern+Gent&background=0D8ABC&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=800",
                'mo_ta' => 'Salon tóc chuyên nghiệp với phong cách hiện đại, chuyên các kiểu tóc Fade và Undercut.',
                'ma_so_thue' => '0315667788',
                'ma_bin_ngan_hang' => '970436', 
                'tai_khoan_ngan_hang' => '19034567891011',
                'diem_hai_long' => 4.8,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 2,
                'id_danh_muc_dich_vu' => 6,
                'ten_thuong_hieu' => 'Zen Spa & Massage Trị Liệu',
                'dia_chi' => '246 Lý Tự Trọng, Phường Bến Thành, Quận 1, TP.HCM',
                'so_dien_thoai' => '0988777666',
                'logo' => "https://ui-avatars.com/api/?name=Zen+Spa&background=55efc4&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=800",
                'mo_ta' => 'Spa & Massage cao cấp với không gian thư giãn và liệu pháp đá nóng chuyên sâu.',
                'ma_so_thue' => '0314223344',
                'ma_bin_ngan_hang' => '970415', 
                'tai_khoan_ngan_hang' => '0071001234567',
                'diem_hai_long' => 4.5,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 3,
                'id_danh_muc_dich_vu' => 7,
                'ten_thuong_hieu' => 'Nail Art Studio Hoàn Mỹ',
                'dia_chi' => 'Hẻm 12, Số 4 Đoàn Văn Bơ, Phường 9, Quận 4, TP.HCM',
                'so_dien_thoai' => '0934112233',
                'logo' => "https://ui-avatars.com/api/?name=Hoan+My+Nail&background=fab1a0&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1604654894610-df4906687103?q=80&w=800",
                'mo_ta' => 'Dịch vụ làm móng chuyên nghiệp với thiết kế sáng tạo và chất lượng sơn nhập khẩu.',
                'ma_so_thue' => '0319887766',
                'ma_bin_ngan_hang' => '970418', 
                'tai_khoan_ngan_hang' => '1015667788',
                'diem_hai_long' => 4.2,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 4,
                'id_danh_muc_dich_vu' => 8,
                'ten_thuong_hieu' => 'Phòng Khám Quốc Tế Clinic Plus',
                'dia_chi' => '45-47 Trần Hưng Đạo, Quận 1, TP.HCM',
                'so_dien_thoai' => '0283911223',
                'logo' => "https://ui-avatars.com/api/?name=Clinic+Plus&background=00cec9&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=800",
                'mo_ta' => 'Clinic chuyên khoa với đội ngũ bác sĩ giàu kinh nghiệm và trang thiết bị hiện đại.',
                'ma_so_thue' => '0311223344',
                'ma_bin_ngan_hang' => '970405', 
                'tai_khoan_ngan_hang' => '001100123456',
                'diem_hai_long' => 4.9,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 5,
                'id_danh_muc_dich_vu' => 9,
                'ten_thuong_hieu' => 'Bệnh viện Đa khoa Tâm Anh',
                'dia_chi' => '2B Phổ Quang, Phường 2, Quận Tân Bình, TP.HCM',
                'so_dien_thoai' => '02871026789',
                'logo' => "https://ui-avatars.com/api/?name=Tam+Anh&background=0984e3&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=800",
                'mo_ta' => 'Bệnh viện đa khoa chuẩn quốc tế với dịch vụ chăm sóc sức khỏe toàn diện.',
                'ma_so_thue' => '0312556677',
                'ma_bin_ngan_hang' => '970422', 
                'tai_khoan_ngan_hang' => '111222333444',
                'diem_hai_long' => 4.7,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 6,
                'id_danh_muc_dich_vu' => 10,
                'ten_thuong_hieu' => 'Tai Mũi Họng Sài Gòn Center',
                'dia_chi' => '1-3 Trịnh Văn Cấn, Quận 1, TP.HCM',
                'so_dien_thoai' => '0903123456',
                'logo' => "https://ui-avatars.com/api/?name=ENT+Center&background=a29bfe&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800",
                'mo_ta' => 'Bệnh viện chuyên khoa với dịch vụ chăm sóc sức khỏe chuyên sâu vùng Tai Mũi Họng.',
                'ma_so_thue' => '0313445566',
                'ma_bin_ngan_hang' => '970423', 
                'tai_khoan_ngan_hang' => '555666777888',
                'diem_hai_long' => 4.4,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 7,
                'id_danh_muc_dich_vu' => 11,
                'ten_thuong_hieu' => 'Nha khoa Smile Sài Gòn',
                'dia_chi' => '321 Đường số 7, Quận Bình Tân, TP.HCM',
                'so_dien_thoai' => '0912445566',
                'logo' => "https://ui-avatars.com/api/?name=Smile+Dental&background=ffeaa7&color=000",
                'anh_bia' => "https://images.unsplash.com/photo-1629909613654-28e377c37b09?q=80&w=800",
                'mo_ta' => 'Phòng khám nha khoa với dịch vụ niềng răng, bọc sứ thẩm mỹ chuyên nghiệp.',
                'ma_so_thue' => '0314556677',
                'ma_bin_ngan_hang' => '970407', 
                'tai_khoan_ngan_hang' => '222333444555',
                'diem_hai_long' => 4.8,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 8,
                'id_danh_muc_dich_vu' => 12,
                'ten_thuong_hieu' => 'Điện lạnh Gia Định chi nhánh 1',
                'dia_chi' => '789 Xô Viết Nghệ Tĩnh, Quận Bình Thạnh, TP.HCM',
                'so_dien_thoai' => '0908112233',
                'logo' => "https://ui-avatars.com/api/?name=Gia+Dinh+Electric&background=74b9ff&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1621905251918-48416bd8575a?q=80&w=800",
                'mo_ta' => 'Dịch vụ sửa chữa điều hòa, tủ lạnh tại nhà nhanh chóng và chuyên nghiệp.',
                'ma_so_thue' => '0315667700',
                'ma_bin_ngan_hang' => '970416', 
                'tai_khoan_ngan_hang' => '190012345678',
                'diem_hai_long' => 4.1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 9,
                'id_danh_muc_dich_vu' => 13,
                'ten_thuong_hieu' => 'Cấp Nước 24h Hoàn Kiếm',
                'dia_chi' => '156 Cao Lỗ, Phường 4, Quận 8, TP.HCM',
                'so_dien_thoai' => '0944123123',
                'logo' => "https://ui-avatars.com/api/?name=Water+24h&background=81ecec&color=000",
                'anh_bia' => "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800",
                'mo_ta' => 'Dịch vụ thông tắc, sửa chữa ống nước chuyên nghiệp có mặt sau 15 phút.',
                'ma_so_thue' => '0316778899',
                'ma_bin_ngan_hang' => '970432', 
                'tai_khoan_ngan_hang' => '102233445566',
                'diem_hai_long' => 4.3,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 10,
                'id_danh_muc_dich_vu' => 14,
                'ten_thuong_hieu' => 'TechPro Electronics Center',
                'dia_chi' => '321 Lê Văn Sỹ, Phường 13, Quận 3, TP.HCM',
                'so_dien_thoai' => '0907445566',
                'logo' => "https://ui-avatars.com/api/?name=Tech+Pro&background=636e72&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1550009158-9ebf69173e03?q=80&w=800",
                'mo_ta' => 'Dịch vụ sửa chữa laptop, điện thoại và thiết bị điện tử với linh kiện chính hãng.',
                'ma_so_thue' => '0317889900',
                'ma_bin_ngan_hang' => '970441', 
                'tai_khoan_ngan_hang' => '190333444555',
                'diem_hai_long' => 4.6,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 11,
                'id_danh_muc_dich_vu' => 15,
                'ten_thuong_hieu' => 'Paws Pet Care Center',
                'dia_chi' => '124 Nguyễn Thị Thập, Tân Hưng, Quận 7, TP.HCM',
                'so_dien_thoai' => '0909556677',
                'logo' => "https://ui-avatars.com/api/?name=Paws+Pet&background=fdcb6e&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=800",
                'mo_ta' => 'Dịch vụ chăm sóc thú cưng toàn diện: Spa, khách sạn và phòng khám thú y.',
                'ma_so_thue' => '0318990011',
                'ma_bin_ngan_hang' => '970429', 
                'tai_khoan_ngan_hang' => '001100456789',
                'diem_hai_long' => 4.9,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 12,
                'id_danh_muc_dich_vu' => 8,
                'ten_thuong_hieu' => 'TMV Korea Beauty Sài Gòn',
                'dia_chi' => '456 Đường LMN, Phường Võ Thị Sáu, Quận 3, TP.HCM',
                'so_dien_thoai' => '0909123456',
                'logo' => "https://ui-avatars.com/api/?name=Korea+Beauty&background=fd79a8&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1560750588-73207b1ef5b8?q=80&w=800",
                'mo_ta' => 'Thẩm mỹ viện chuẩn Hàn Quốc với công nghệ trẻ hóa da và nâng cơ hiện đại nhất.',
                'ma_so_thue' => '0319112233',
                'ma_bin_ngan_hang' => '970436', 
                'tai_khoan_ngan_hang' => '999888777666',
                'diem_hai_long' => 5.0,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 13,
                'id_danh_muc_dich_vu' => 12,
                'ten_thuong_hieu' => 'Điện máy Xanh Service Pro',
                'dia_chi' => '789 Đường Bạch Đằng, Quận Bình Thạnh, TP.HCM',
                'so_dien_thoai' => '0908777888',
                'logo' => "https://ui-avatars.com/api/?name=Dien+May+Xanh&background=0984e3&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=800",
                'mo_ta' => 'Dịch vụ bảo trì và sửa chữa điện máy tận nhà với quy trình chuyên nghiệp.',
                'ma_so_thue' => '1112223334',
                'ma_bin_ngan_hang' => '970422',
                'tai_khoan_ngan_hang' => '123123123000',
                'diem_hai_long' => 4.2,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_nha_cung_cap' => 14,
                'id_danh_muc_dich_vu' => 15,
                'ten_thuong_hieu' => 'Pet Paradise Resort & Spa',
                'dia_chi' => '321 Đường Nguyễn Lương Bằng, Quận 7, TP.HCM',
                'so_dien_thoai' => '0907111222',
                'logo' => "https://ui-avatars.com/api/?name=Pet+Paradise&background=00b894&color=fff",
                'anh_bia' => "https://images.unsplash.com/photo-1548191265-cc70d3d45ba1?q=80&w=800",
                'mo_ta' => 'Nghỉ dưỡng cao cấp cho thú cưng với hồ bơi và khu vui chơi riêng biệt.',
                'ma_so_thue' => '8887779991',
                'ma_bin_ngan_hang' => '970407',
                'tai_khoan_ngan_hang' => '456456456789',
                'diem_hai_long' => 4.7,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}